---
title: Feature Value
---
flowchart TD
    subgraph Attribute1
        Value1_A1
        Value2_A1
    end
    subgraph Attribute2
        Value1_A2
        Value2_A2
    end

    Value1_A1 --- Value1_A2
    Value2_A1 --- Value2_A2